### ISSUE TITLE
[Feature Request] ability to blacklist items from being stored in graves

### ISSUE THREAD

**Issue by virtualonno** [Flanks255/simply-graves#1]
Is it possible to add an option to exclude certain items from being stored in graves, regardless of whether users opt-in to them?

For context, I am running a 1.19.2 PvP server in which I would like to use graves (the grave protection timer is excellent for this) but also want for players to have certain token items or valuables at risk, even with a grave its protection.

Thanks for developing this intuitive and effective mod!

**Comment by Flanks255** [comment]
Good idea, ill knock this out after i port MGU 👍
