### ISSUE TITLE
Graves cannot place in claimed FTB chunks

### ISSUE THREAD

**Issue by Alainx277** [Flanks255/simply-graves#3]
## Bug

When a player dies in a chunk that was claimed by another player with the FTB Chunks mod, the grave cannot be placed.

```
[Server thread/INFO] [minecraft/MinecraftServer]: PLAYER_NAME fell from a high place
[Server thread/INFO] [co.fl.si.SimplyGraves/]: Grave for PLAYER_NAME failed to place.
```

## Possible solutions

It would be nice if the grave could place in claimed chunks (and also be retrievable by the player).

Alternatively the player could be reminded in chat to use `/simplygraves failed` when a grave fails to place.

## Versions

NeoForge 47.1.76
Simply Graves 1.20.1-1.0.7-build.8
FTB Chunks 2001.2.3

**Comment by Flanks255** [comment]
I still need to test this with just SG and chunks, but i talked to the maintainer of ftb chunks and they said it should not block it, as i am directly placing the block in the level.

Also the mod does show a message in your chat when a grave fails to place, along with a clickable link that recovers it.
